"use client";

import { Provider } from "react-redux";
import "./globals.css";
import store from "@/redux/store/store";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={``}>{children}</body>
      </Provider>
    </html>
  );
}
